openapi: 3.0.3
info:
  title: Auth
  version: 1.0.0
paths:
  /api/auth/login:
    post:
      summary: Login to obtain access token
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: admin
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id: { type: string }
                      username: { type: string }
                      role: { type: string }
                      createdAt: { type: string, format: date-time }
                  token:
                    type: string
        "401":
          description: Invalid credentials
