openapi: 3.0.3
info:
  title: Courses
  version: 1.0.0
paths:
  /api/courses:
    get:
      summary: List courses
      tags: [Courses]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            example: 1
        - in: query
          name: limit
          schema:
            type: integer
            example: 10
        - in: query
          name: difficulty
          schema:
            type: string
            enum: [Beginner, Intermediate, Advanced]
        - in: query
          name: search
          schema:
            type: string
      responses:
        "200":
          description: Success
    post:
      summary: Create a course
      tags: [Courses]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, description, difficulty]
              properties:
                title:
                  type: string
                description:
                  type: string
                difficulty:
                  type: string
                  enum: [Beginner, Intermediate, Advanced]
      responses:
        "201":
          description: Created
        "400":
          description: Validation error
        "401":
          description: Unauthorized
